Bump `unicode-loose-match`
node-unicode/node-unicode-data pull request #72
Opened 2023-08-21 15:25 UTC by JLHwung

Actually bump `unicode-loose-match` and fix the assertion guard when `unicode-loos-match` is out of dated.

Also added a minimal GH test workflow.

Fixes #71

2023-08-22 06:14 UTC, mathiasbynens requested changes

2023-08-22 06:14 UTC, mathiasbynens commented on .github/workflows/ci.yml
> +                node-version: latest
Let’s keep `.nvmrc` as the single source of truth, i.e. update the version number in it and then refer to it here:

```suggestion
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
```

(also let’s use two-space indents?)

2023-08-22 06:15 UTC, mathiasbynens commented on .github/workflows/ci.yml
> +              run: npm run test
```suggestion
              run: npm test
```

2023-08-24 13:33 UTC, JLHwung commented
@mathiasbynens 🏓

2023-08-25 08:01 UTC, mathiasbynens approved these changes

2023-08-25 08:01 UTC, merged

2023-08-25 08:58 UTC, mathiasbynens commented
Thanks!